### ISSUE TITLE
Highlight post layout

### ISSUE THREAD

**Issue by oscarmcm** [gdg-managua/jekyll-mdl#1]
When the highlight post are used, for some strange reasons the margin between nav and the post not work.

![image](https://cloud.githubusercontent.com/assets/2553459/8686032/fcb4ea36-2a3f-11e5-8c3b-0d59d2582fd7.png)

**Comment by byroncorrales** [comment]
[Fixed](https://github.com/gdg-managua/jekyll-mdl/commit/9b6a911235243cd42a4ca8be42fe42866ffc57d0)
