### ISSUE TITLE
post_type: highlight

### ISSUE THREAD

**Issue by thomasweld** [gdg-managua/jekyll-mdl#14]
Original comment:
"What makes a blog post "higlighted" ?

site.post_type == 'highlight'

I don't see this label on any of the posts .. is there a setting somewhere to "hilight" blogs by date or something else??"

Most recent blog post is automatically highlighted as a result of the _config.yml file .. however, is there a way we can specify another method of choosing which post is highlighted (like a pinned tweet or something similar). 

Thanks,

Thomas

**Comment by oscarmcm** [comment]
Hi Thomas

Thanks for open the issue.

Now the jekyll-mdl post have the option for decide which post is highlighted or not.

Please see #13 

Saludos

**Comment by thomasweld** [comment]
Thanks !!
