### ISSUE TITLE
Bug in Search input

### ISSUE THREAD

**Issue by forsureitsme** [gdg-managua/jekyll-mdl#19]
I was testing the mobile responsiveness of this theme, and when I came to the search box and typed "this is long search term" it broke...

![image](https://cloud.githubusercontent.com/assets/2235293/10230753/3c2ab062-6855-11e5-9337-9aa0c87eb031.png)

**Comment by forsureitsme** [comment]
If this helps, [the Dashboard example](http://www.getmdl.io/templates/dashboard/index.html) from [Google's MDL Repository](https://github.com/google/material-design-lite) has the search working with a different approach by the same resolution.

**Comment by oscarmcm** [comment]
Fixed
<img width="315" alt="imagen" src="https://user-images.githubusercontent.com/2553459/41547837-83f2239e-72de-11e8-9dc0-6a3d292f9a0c.png">

Thanks
