### ISSUE TITLE
Highlight post and cards

### ISSUE THREAD

**Issue by oscarmcm** [gdg-managua/jekyll-mdl#2]
When the highlight post are used, this don't have the same margins with the cards

![image](https://cloud.githubusercontent.com/assets/2553459/8686093/7b4195f2-2a40-11e5-9a52-8a10829aa963.png)

**Comment by byroncorrales** [comment]
fixed

**Comment by oscarmcm** [comment]
[Fixed](https://github.com/gdg-managua/jekyll-mdl/commit/9b6a911235243cd42a4ca8be42fe42866ffc57d0)
