### ISSUE TITLE
Unconventional use of floating action button

### ISSUE THREAD

**Issue by not-much-io** [gdg-managua/jekyll-mdl#23]
Using a floating action button on each card (as on demo page) is a discouraged practice by MD standards. :) 

"Only one floating action button is recommended per screen to increase its prominence. It should represent only the most common action."

Source: https://www.google.de/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button 

A fix would be to simply use a second link on the card as in the first example here -> http://materializecss.com/cards.html

**Comment by oscarmcm** [comment]
Fixed in #24 thanks @not-much-io :+1:
