### ISSUE TITLE
Button in card post

### ISSUE THREAD

**Issue by oscarmcm** [gdg-managua/jekyll-mdl#3]
The read_more button in the card need some cool align, for now the button is something like thath

![image](https://cloud.githubusercontent.com/assets/2553459/8687101/183ba146-2a4a-11e5-9e27-13e8d3a083c4.png)

But we need something like this
![image](https://cloud.githubusercontent.com/assets/2553459/8687142/6e039110-2a4a-11e5-8d06-a43ad9ba4b71.png)

**Comment by byroncorrales** [comment]
Done

**Comment by oscarmcm** [comment]
[Fixed](https://github.com/gdg-managua/jekyll-mdl/commit/df6d609a5b88e8c4adb4a2c5e34b2c13e1a6b973)
