### ISSUE TITLE
Multiple highlighted posts breaks share button

### ISSUE THREAD

**Issue by hallelulius** [gdg-managua/jekyll-mdl#31]
When using multiple highlighted post there is an issue with the share button. The most recent one works but opens all share buttons on highlighted posts. An easy fix would be to include the post name in the id of the button and for in the ul like: 

``` html
<button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="btn-high-{{ post.title }}">
<ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right" for="btn-high-{{ post.title }}">
```

**Comment by oscarmcm** [comment]
Fixed #32 

Thanks @hallelulius :+1:
