### ISSUE TITLE
Nested lists don't work

### ISSUE THREAD

**Issue by noizbuster** [gdg-managua/jekyll-mdl#33]
Nested lists don't work in post.
I tested rdiscount, redcarpet, kramdown

by the way, it works well on jekyll-commonmark

**Comment by oscarmcm** [comment]
Hi @noizbuster,

I don't  understand what is your problem, can you attach a screenshot or a traceback?

Thanks

**Comment by noizbuster** [comment]
![image](https://cloud.githubusercontent.com/assets/8962065/12190679/e1944214-b60e-11e5-86e7-e7798964daf5.png)

oh.. that was my mistake.
It only happens when I try to use the rdiscount

**Comment by oscarmcm** [comment]
I think this is a problem with your markdown compiler and not with the theme directly. Check if ruby and jekyll is correctly instaled 

btw nested list 

``` md

1. Dog
    1. German Shepherd
    2. Belgian Shepherd
        1. Malinois
        2. Groenendael
        3. Tervuren
2. Cat
    1. Siberian
    2. Siamese
```

Will produce something like this 
1. Dog
   1. German Shepherd
   2. Belgian Shepherd
      1. Malinois
      2. Groenendael
      3. Tervuren
2. Cat
   1. Siberian
   2. Siamese

I think this is as close as you can get; Markdown doesn't support the "1.1.1" type list you wanted
