### ISSUE TITLE
Only two of the variables in main.scss do anything

### ISSUE THREAD

**Issue by brianthelion** [gdg-managua/jekyll-mdl#34]
This still compiles:

``` sass
$spacing-unit:     30px;
//$text-color:       #111;
//$background-color: #fdfdfd;
//$brand-color:      #2a7ae2;
$grey-color:       #828282;
$grey-color-light: lighten($grey-color, 40%);
//$grey-color-dark:  darken($grey-color, 25%);
```

Which brings up a larger question: How do you override the colors set by the mdl stylesheet in `_includes/head.html`?

**Comment by oscarmcm** [comment]
@brianthelion thanks for notify the unused variables.

At this moment, we don't have a way to change the default colors. You have some idea how we can override the colors? From the [README.md](https://github.com/gdg-managua/jekyll-mdl#custom-themes)

> If you don't want the default site colors, you can create custom themes for the site in the [mdl theme creator](http://www.getmdl.io/customize/index.html). The site will create a custom css, something like this:  `<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.teal-green.min.css" />` Now add this in the _includes/head.html file, under the main css and enjoy your new theme.

Hope that this will help you.

Un abrazo!

**Comment by oscarmcm** [comment]
Remove unused vars in #40
