### ISSUE TITLE
Post Layout Template

### ISSUE THREAD

**Issue by oscarmcm** [gdg-managua/jekyll-mdl#4]
If you see the new layout for the post... the main divider don't use the 100% of the page ![image](https://cloud.githubusercontent.com/assets/2553459/8760359/b0bc57f8-2cd4-11e5-9b2f-753960c7357c.png)

this is caused because the class

.page-content {
  max-width: 1200px;
  margin: 0 auto;
}

have a max-width, if you remove this, then the main dividir use the 100% of the layout, but be careful, if you remove this, the post list will change his layout.

**Comment by AdrienLemaire** [comment]
I have some doubts about the layout, the about page doesn't look good at all to me:

![about](https://cloud.githubusercontent.com/assets/260983/8770744/179540ec-2ef2-11e5-97d3-1f4cd13e8179.png)

For example, shouldn't the footer minimum stick at the bottom of the page ? Here the bottom half of the page is white.

Also in 

![post_ribbon](https://cloud.githubusercontent.com/assets/260983/8770760/6ba34922-2ef2-11e5-859e-b1a357de1c47.png)

This "ribbon" is taking two third of the post. It doesn't look anymore like a ribbon, but more like a container color, container overflowed by the post.

Not sure about the good fixes to do, I need to study a bit about material design.

**Comment by oscarmcm** [comment]
@Fandekasp I think that its a problem with our layout, im workon on it :smile: thanks :+1:

**Comment by oscarmcm** [comment]
Fixed
