### ISSUE TITLE
Format loss when uploaded on github

### ISSUE THREAD

**Issue by vbursucianu** [gdg-managua/jekyll-mdl#42]
Here is two screenshots taken when the site is generated localy and when it is live on github 
![github](https://cloud.githubusercontent.com/assets/10605722/13308377/cbd773ae-db40-11e5-89f4-4931af0df313.png)
![local](https://cloud.githubusercontent.com/assets/10605722/13308378/cbd795dc-db40-11e5-8626-91c3058be384.png)

**Comment by oscarmcm** [comment]
@vbursucianu set baseURL in your [_config.yml](https://github.com/gdg-managua/jekyll-mdl/blob/master/_config.yml#L8)
