### ISSUE TITLE
Layout broken on Safari

### ISSUE THREAD

**Issue by MeoBeoI** [gdg-managua/jekyll-mdl#46]
When I check [http://webiphany.com](http://webiphany.com), layout is borken.

![Imgur](http://i.imgur.com/uDxBkAR.png)

Console of safari is clear, don't have any warning or error.

Mac : OSX 10.11.5
Safari : 9.1.1

**Comment by oscarmcm** [comment]
Fixed 
<img width="1440" alt="imagen" src="https://user-images.githubusercontent.com/2553459/41547700-2a4e803a-72de-11e8-8896-dd9aac4069dd.png">

Thanks
