### ISSUE TITLE
Closing the drawer?

### ISSUE THREAD

**Issue by ghost** [gdg-managua/jekyll-mdl#54]
Is there any way I can make it so that the drawer will close when the user clicks away from it?

**Comment by DecWebb** [comment]
I do not know the exact code but the original jekyll-mdl theme had that feature to allow the draw to close when the user clicked away. I am too inexperienced with web development to find the issue from looking at your repo. I suggest looking for differences in the files in the includes, layouts, sass and css folders as these are the main ones which generate the website.

**Comment by oscarmcm** [comment]
It auto closes when user click away from the drawer
