### ISSUE TITLE
"Demo" button on theme gallery site redirects to wrong site

### ISSUE THREAD

**Issue by aschrijver** [gdg-managua/jekyll-mdl#56]
The gallery site at `http://jekyllthemes.org/themes/jekyll-mdl/` when clicking "Demo" button has the URL http://www.gdgmanagua.org/jekyll-mdl configured, which redirects to
`https://nieuws-nl.com/telegraaf/coolblue/?lpkey=153041c788e7169616&uclick=irm7hefe`

Maybe someone else took over that domain name? You should probably get it updated.

**Comment by oscarmcm** [comment]
@aschrijver yeah, we lost the main domain name, but you can see a demo on this url http://gdgmanagua.github.io/jekyll-mdl/ and maybe you can send a PR to Jekyll Themes updating the url too 😄 Thanks!

**Comment by byroncorrales** [comment]
Url fixed
