### ISSUE TITLE
Cant find css files

### ISSUE THREAD

**Issue by AdrianoCelentano** [gdg-managua/jekyll-mdl#58]
i cloned the repo and run jekyll, without changing any files.
I got the following error
```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'jekyll-mdl/css/main.scss':
                    File to import not found or unreadable: base. on line 16
```

I tried to add the path of the css files to the config file and i tried to add the path directly to the import statement. Both unfortunately didnt work for me. Any help would be much appreciated.

**Comment by oscarmcm** [comment]
Hi @AdrianoCelentano I tried to replicate this bug, but seems to worked as expected, seems to be related to your sass gem version, maybe updating this could fix on yiur end, I'm going to close this issue, but feel free to reopen if the problem persist.
