### ISSUE TITLE
indigo theme colors hard-coded

### ISSUE THREAD

**Issue by AdrienLemaire** [gdg-managua/jekyll-mdl#6]
It would be great if only colors from the Material Design Lite css Library were used. If I change the theme from indigo-pink to green-orange, I'll still see several wrong colors around the blog, for example in `_sass/_post.scss`  **.post-ribbon.background-color**.

Is that possible ?

**Comment by oscarmcm** [comment]
@Fandekasp thanks for report this, we change the color in the post-ribbon for something more pleasant and generic.

For now if you want to change the color you need edit the file, this block is don't be able for use a color from another material theme.

Hope it will help you.

Regards.

**Comment by AdrienLemaire** [comment]
@oscarmcm as said on Twitter, I unfortunately changed my theme (I should reactivate email notification on github messages), but you're doing a great job :D  Awesome reaction !
