### ISSUE TITLE
Broken vertical "more" menu

### ISSUE THREAD

**Issue by AdrienLemaire** [gdg-managua/jekyll-mdl#7]
![more_vert](https://cloud.githubusercontent.com/assets/260983/8771335/7e56ea98-2efb-11e5-969b-348f3a1ac673.png)

I think we're supposed to see the menu items "Some Action", "Another Action", "Disabled Action" and "Yet Another Action" when clicking on the top right button

**Comment by AdrienLemaire** [comment]
Search feature seems broken too.

**Comment by AdrienLemaire** [comment]
After further investigation, it seems like this is my Chromium browser who is broken (or chrome related css rules. Running Version 43.0.2357.130 (64-bit) .

Menu is shown correctly on firefox, but search box still broken.

**Comment by oscarmcm** [comment]
[Fixed](https://github.com/gdg-managua/jekyll-mdl/commit/4094c0c2f6ef9a2ed33d6f8c274fc9c88657e5d7)
